# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - ./pg-dump:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"


  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080
